collections:
  posts: '/post/{slug}'
  placecol: '/places/{slug}'
  places: '/places/{slug}'
taxonomies:
  categories: '/category/{slug}'
  country: '/country/{slug}'
routes:
  /:
    template: home
    title: Home
  /posts:
    template: 'posts/index'
    title: All Posts
  /places:
    template: 'places/index'
    title: All Places
